name: First workflow

on: [ push ]

jobs:
  xyz:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Hello world
        run: echo "Hello world! from ${{ github.workflow }} triggered by the {{ github.event_name }} done by ${{ github.actor }}"
